### ISSUE TITLE
mod not working as of update #89

### ISSUE THREAD

**Issue by sundavar91** [WallyCZ/DVRouteManager#1]
when trying to create new routes or use the ai for shunting the screen freezes and you cant do anything else with the comm radio
counsel error messages reads 
null reference exception object not set to an instance of an object

**Comment by WallyCZ** [comment]
Tried to handle that update changes, release for testing: https://github.com/WallyCZ/DVRouteManager/releases/download/0.3.2/DVRouteManager.zip
