### ISSUE TITLE
Route Manager for build #89 + is working but....

### ISSUE THREAD

**Issue by ct8402** [WallyCZ/DVRouteManager#2]
New problem with Route Manager update:  First: it works well.  However, on quitting the game, the mod reverts to the earlier update (0.3.1), even when the earlier one is not installed (I made sure of this).  I must re-update the mod in UMM every time I quit the game to keep using it.  The sounds in the mod do not work either.

**Comment by WallyCZ** [comment]
It's because version 0.3.2 is not published yet. Workaround is edit (f.e. in notepad) "Derail Valley\Mods\DVRouteManager\Info.json"
And replace
`    "Version": "0.3.2",`
to
`    "Version": "0.3.1",`

I will look on the sound issue.

**Comment by ct8402** [comment]
Thanks Wally!  Followed your instructions and it's working as advertised.
