### ISSUE TITLE
Route Manager throws an error when creating a route

### ISSUE THREAD

**Issue by GaelKo** [WallyCZ/DVRouteManager#3]
Hi, the route manager doesn't work for the build #90 of the game. It throws an error in the console when I'm trying to create a new route from job cars to destination. 

![error](https://user-images.githubusercontent.com/66775496/107794023-3a24ba80-6d57-11eb-9ae0-db4165031476.PNG)

Thank you!

**Comment by odwales20** [comment]
im getting the same issue

**Comment by DominoX** [comment]
Same error. Build #91 (Boombox). Using non-VR gameplay option at startup

**Comment by WallyCZ** [comment]
Should be solved with this version https://github.com/WallyCZ/DVRouteManager/releases/tag/0.3.3
