### ISSUE TITLE
Well, I think they did it again with #91

### ISSUE THREAD

**Issue by ct8402** [WallyCZ/DVRouteManager#4]
So far, since Build 91, Route Manager works, except for a couple of features.  It will plan a route, move the switches, but will not auto-reverse on shunting OR "Job Routes", when selecting "Route Tracker" all I get is "Go to Start Position", and nothing else.  Also, in case this is important, route display on the map is permanent, the entire route displays all the time, the train doesn't "pick up" the route display as it goes along the route.  NOTE: if I'm wrong about this map issue, I can't go back and confirm this problem!

**Comment by RSDNTWK** [comment]
You're not the only one. We've confirmed the issues as well on a new save.

**Comment by RSDNTWK** [comment]
@ct8402 You're not the only one. We've confirmed the issues as well on a new save with no other mods installed.

**Comment by WallyCZ** [comment]
Should be solved with this version https://github.com/WallyCZ/DVRouteManager/releases/tag/0.3.3

**Comment by ct8402** [comment]
Works great and thanks very much Wally!
